### ISSUE TITLE
ubuntu 14.04 node v0.10.25 run error

### ISSUE THREAD

**Issue by goog** [hanhui03/jstruct#1]
```bash
cheng@cheng-virtual-machine:~/jstruct$ node jstruct.js conf.json

/home/cheng/jstruct/jstruct.js:72
        for (var item of member) {
                      ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

**Comment by goog** [comment]
update to v12.22.5 ok.

**Comment by hanhui03** [comment]
^-^
